[package]
name = "diffident-ui"
version.workspace = true
edition.workspace = true

[dependencies]
diffident-model.workspace = true
diffident-diff.workspace = true
diffident-forge.workspace = true
diffident-highlight.workspace = true
diffident-session.workspace = true
gpui.workspace = true
serde_json.workspace = true
